POST {{ api }}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

> {%
    const data = response.body['data'];

    const token = data['token'];

    client.global.set('token', token);
 %}

###

POST {{api}}/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}
